// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   spendme/v1
// Description:
//   SpendMe API

#if GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRObject.h"
#else
  #import "GTLRObject.h"
#endif

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

@class GTLRSpendme_Expense;

NS_ASSUME_NONNULL_BEGIN

/**
 *  GTLRSpendme_Expense
 */
@interface GTLRSpendme_Expense : GTLRObject

@property(copy, nullable) NSString *category;
@property(copy, nullable) NSString *comment;
@property(copy, nullable) NSString *entityKey;

/**
 *  expense
 *
 *  Uses NSNumber of doubleValue.
 */
@property(strong, nullable) NSNumber *expense;

@property(copy, nullable) NSString *lastTouchDateTime;
@property(copy, nullable) NSString *when;

@end


/**
 *  GTLRSpendme_ExpenseCollection
 *
 *  @note This class supports NSFastEnumeration and indexed subscripting over
 *        its "items" property. If returned as the result of a query, it should
 *        support automatic pagination (when @c shouldFetchNextPages is
 *        enabled).
 */
@interface GTLRSpendme_ExpenseCollection : GTLRCollectionObject

/**
 *  items
 *
 *  @note This property is used to support NSFastEnumeration and indexed
 *        subscripting on this class.
 */
@property(strong, nullable) NSArray<GTLRSpendme_Expense *> *items;

@property(copy, nullable) NSString *nextPageToken;

@end

NS_ASSUME_NONNULL_END
