// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   spendme/v1
// Description:
//   SpendMe API

#if GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRQuery.h"
#else
  #import "GTLRQuery.h"
#endif

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

@class GTLRSpendme_Expense;

NS_ASSUME_NONNULL_BEGIN

/**
 *  Parent class for other Spendme query classes.
 */
@interface GTLRSpendmeQuery : GTLRQuery

/** Selector specifying which fields to include in a partial response. */
@property(copy, nullable) NSString *fields;

@end

/**
 *  Delete the given expense if present
 *
 *  Method: spendme.spendme.delete
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeSpendmeUserinfoEmail
 */
@interface GTLRSpendmeQuery_SpendmeDelete : GTLRSpendmeQuery
// Previous library name was
//   +[GTLQuerySpendme queryForSpendmeDeleteWithentityKey:]

@property(copy, nullable) NSString *entityKey;

/**
 *  Fetches a @c GTLRSpendme_Expense.
 *
 *  Delete the given expense if present
 *
 *  @param entityKey NSString
 *
 *  @returns GTLRSpendmeQuery_SpendmeDelete
 */
+ (instancetype)queryWithEntityKey:(NSString *)entityKey;

@end

/**
 *  Insert a expense
 *
 *  Method: spendme.spendme.insert
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeSpendmeUserinfoEmail
 */
@interface GTLRSpendmeQuery_SpendmeInsert : GTLRSpendmeQuery
// Previous library name was
//   +[GTLQuerySpendme queryForSpendmeInsertWithObject:]

/**
 *  Fetches a @c GTLRSpendme_Expense.
 *
 *  Insert a expense
 *
 *  @param object The @c GTLRSpendme_Expense to include in the query.
 *
 *  @returns GTLRSpendmeQuery_SpendmeInsert
 */
+ (instancetype)queryWithObject:(GTLRSpendme_Expense *)object;

@end

/**
 *  Return all the expenses
 *
 *  Method: spendme.spendme.list
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeSpendmeUserinfoEmail
 */
@interface GTLRSpendmeQuery_SpendmeList : GTLRSpendmeQuery
// Previous library name was
//   +[GTLQuerySpendme queryForSpendmeList]

@property(assign) long long limit;

@property(copy, nullable) NSString *order;

@property(copy, nullable) NSString *pageToken;

/**
 *  Fetches a @c GTLRSpendme_ExpenseCollection.
 *
 *  Return all the expenses
 *
 *  @returns GTLRSpendmeQuery_SpendmeList
 *
 *  @note Automatic pagination will be done when @c shouldFetchNextPages is
 *        enabled. See @c shouldFetchNextPages on @c GTLRService for more
 *        information.
 */
+ (instancetype)query;

@end

NS_ASSUME_NONNULL_END
