// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   spendme/v1
// Description:
//   SpendMe API

#import "GTLRSpendme.h"

// ----------------------------------------------------------------------------
// Authorization scope

NSString * const kGTLRAuthScopeSpendmeUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";

// ----------------------------------------------------------------------------
//   GTLRSpendmeService
//

@implementation GTLRSpendmeService

- (instancetype)init {
  self = [super init];
  if (self) {
    // From discovery.
    self.rootURLString = @"https://max-spendme.appspot.com/_ah/api/";
    self.servicePath = @"spendme/v1/spendme/";
    self.batchPath = @"batch";
    self.prettyPrintQueryParameterNames = @[ @"prettyPrint" ];
  }
  return self;
}

@end
