// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   spendme/v1
// Description:
//   SpendMe API

#import "GTLRSpendmeObjects.h"
#import "GTLRSpendmeQuery.h"
#import "GTLRSpendmeService.h"
