// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   spendme/v1
// Description:
//   SpendMe API

#import "GTLRSpendmeQuery.h"

#import "GTLRSpendmeObjects.h"

@implementation GTLRSpendmeQuery

@dynamic fields;

@end

@implementation GTLRSpendmeQuery_SpendmeDelete

@dynamic entityKey;

+ (instancetype)queryWithEntityKey:(NSString *)entityKey {
  NSArray *pathParams = @[ @"entityKey" ];
  NSString *pathURITemplate = @"delete/{entityKey}";
  GTLRSpendmeQuery_SpendmeDelete *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"DELETE"
                       pathParameterNames:pathParams];
  query.entityKey = entityKey;
  query.expectedObjectClass = [GTLRSpendme_Expense class];
  query.loggingName = @"spendme.spendme.delete";
  return query;
}

@end

@implementation GTLRSpendmeQuery_SpendmeInsert

+ (instancetype)queryWithObject:(GTLRSpendme_Expense *)object {
  if (object == nil) {
    GTLR_DEBUG_ASSERT(object != nil, @"Got a nil object");
    return nil;
  }
  NSString *pathURITemplate = @"insert";
  GTLRSpendmeQuery_SpendmeInsert *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLRSpendme_Expense class];
  query.loggingName = @"spendme.spendme.insert";
  return query;
}

@end

@implementation GTLRSpendmeQuery_SpendmeList

@dynamic limit, order, pageToken;

+ (instancetype)query {
  NSString *pathURITemplate = @"list";
  GTLRSpendmeQuery_SpendmeList *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:nil
                       pathParameterNames:nil];
  query.expectedObjectClass = [GTLRSpendme_ExpenseCollection class];
  query.loggingName = @"spendme.spendme.list";
  return query;
}

@end
